config/routes.rb
AWADNewsApp::Application.routes.draw do

  root :to => 'headlines#index'

  resources :headlines do
      resources :comments
  end
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, :presence => true
  belongs_to :headline
end

app/models/headline.rb
class Headline < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @headline = Headline.find(params[:headline_id])
    @comment = @headline.comments.create(params[:comment])
    redirect_to headline_path(@headline)
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
  # GET /headlines
  # GET /headlines.json
  def index
    @headlines = Headline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @headlines }
    end
  end

  # GET /headlines/1
  # GET /headlines/1.json
  def show
    @headline = Headline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @headline }
    end
  end

  # GET /headlines/new
  # GET /headlines/new.json
  def new
    @headline = Headline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @headline }
    end
  end

  # GET /headlines/1/edit
  def edit
    @headline = Headline.find(params[:id])
  end

  # POST /headlines
  # POST /headlines.json
  def create
    @headline = Headline.new(params[:headline])

    respond_to do |format|
      if @headline.save
        format.html { redirect_to @headline, notice: 'Headline was successfully created.' }
        format.json { render json: @headline, status: :created, location: @headline }
      else
        format.html { render action: "new" }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /headlines/1
  # PUT /headlines/1.json
  def update
    @headline = Headline.find(params[:id])

    respond_to do |format|
      if @headline.update_attributes(params[:headline])
        format.html { redirect_to @headline, notice: 'Headline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headlines/1
  # DELETE /headlines/1.json
  def destroy
    @headline = Headline.find(params[:id])
    @headline.destroy

    respond_to do |format|
      format.html { redirect_to headlines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.description %>
</p>

<p>
  <b>Comment:</b>
  <%= comment.rating %>
</p>v

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Commenter</th>
    <th>Rating</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.description %></td>
    <td><%= comment.commenter %></td>
    <td><%= comment.rating %></td>
    <td><%= comment.references %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @comment.description %>
</p>

<p>
  <b>Commenter:</b>
  <%= @comment.commenter %>
</p>

<p>
  <b>Rating:</b>
  <%= @comment.rating %>
</p>

<p>
  <b>References:</b>
  <%= @comment.references %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/headlines/_form.html.erb
<%= form_for(@headline) do |f| %>
  <% if @headline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@headline.errors.count, "error") %> prohibited this headline from being saved:</h2>

      <ul>
      <% @headline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_area :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/headlines/edit.html.erb
<h1>Editing headline</h1>

<%= render 'form' %>

<%= link_to 'Show', @headline %> |
<%= link_to 'Back', headlines_path %>

app/views/headlines/index.html.erb
<h1>Listing headlines</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Description</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @headlines.each do |headline| %>
  <tr>
    <td><%= headline.title %></td>
    <td><%= headline.date %></td>
    <td><%= headline.description %></td>
    <td><%= headline.link %></td>
<!-- <td><%= link_to 'Show', headline %></td>
       <td><%= link_to 'Edit', edit_headline_path(headline) %></td>
    <td><%= link_to 'Destroy', headline, confirm: 'Are you sure?', method: :delete %></td>
 !-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Headline', new_headline_path %>

app/views/headlines/new.html.erb
<h1>New headline</h1>

<%= render 'form' %>

<%= link_to 'Back', headlines_path %>

app/views/headlines/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Sample change </h1>

<p>
  <b>Title:</b>
  <%= @headline.title %>
</p>

<p>
  <b>Date:</b>
  <%= @headline.date %>
</p>

<p>
  <b>Description:</b>
  <%= @headline.description %>
</p>

<p>
  <b>Link:</b>
  <%= @headline.link %>
</p>

<h2>Comments</h2>
<%= render @headline.comments %>

<h2>Add a comment:</h2>
<%= form_for([@headline, @headline.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_headline_path(@headline) %> |
<%= link_to 'Back', headlines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AWADNewsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Headlines", headline_path %>
<%= link_to "Comments", comment_path %>

<!-- Put page format in here !-->

<%= yield %>

</body>
</html>